######################################################################
# Automatically generated by qmake (2.01a) Thu Apr 18 21:48:06 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
QT      += webkit network
HEADERS += mainwindow.h
SOURCES += main.cpp mainwindow.cpp
